# Generated by Django 2.1.5 on 2019-01-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20190123_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=300)),
                ('age', models.DecimalField(decimal_places=0, max_digits=999)),
            ],
        ),
    ]
